site_name: PgDoorman Documentation
repo_url: https://github.com/ozontech/pg_doorman
site_url: https://ozontech.github.io/pg_doorman/
docs_dir: docs
edit_uri: edit/master/documentation/docs

theme:
  name: material
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/book
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - tables
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
    - index.md
    - 'Getting started':
        - 'tutorials/overview.md'
        - 'tutorials/installation.md'
        - 'tutorials/basic-usage.md'
        - 'tutorials/binary-upgrade.md'
        - 'tutorials/contributing.md'
        - 'changelog.md' 
    - 'reference/settings.md'
    - benchmarks.md
plugins:
  - search
  - autorefs
  - macros:
      verbose: true
      module_name: mkdocs-customizations/macros/docissimo
      include_dir: mkdocs-customizations/macros

extra:
  attributes_path: ../Cargo.toml
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github 
      link: https://ozontech.github.io/pg_doorman/
    - icon: fontawesome/brands/telegram
      link: https://t.me/pg_doorman